### ISSUE TITLE
Drop-in replacement for DBD::mysql?

### ISSUE THREAD

**Issue by greatquux** [gooddata/DBD-MariaDB#11]
I'd like to use this driver as a drop-in replacement for DBD::mysql (the same way MariaDB is a drop-in replacement for MySQL) so that existing code doesn't have to be rewritten to use the new function names.  Aside from reverting all the commits where the function names were changed is there any way to do this?

**Comment by pali** [comment]
Hi! See details in https://github.com/gooddata/DBD-MariaDB/issues/9

**Comment by greatquux** [comment]
Ok - I see your philosophy, it's just a shame I can't use it because of backwards compatibility issues.  Hopefully DBD::mysql will incorporate your changes (or at least try to keep up a bit better) with MariaDB compatibility.

**Comment by pali** [comment]
Anyway, there are no new function names. All functions are according to DBI API (see https://metacpan.org/pod/DBI). And if you are talking about driver private method or attributes, then look at DBI API ([https://metacpan.org/pod/DBI#private_your_module_name_*](https://metacpan.org/pod/DBI#private_your_module_name_*)). Driver private functions needs to start with driver specified prefix, hence it is `mariadb_` instead of `mysql_`. But this is something which DBI-aware application already needs to handle.

Plan for DBD::MariaDB is also to clean up code and fix bugs which are not possible to fix in DBD::mysql. Therefore there would not be full 100% compatibility. We really do not want to include old DBD::mysql bugs into DBD::MariaDB, or having old bugs unfixed forever (e.g. Unicode support).
